version: '3.8'

services:
  yolo:
    build:
      context: .
      dockerfile: Dockerfile.yolo
    network_mode: host
    environment:
      - NVIDIA_VISIBLE_DEVICES=all

  facenet:
    build:
      context: .
      dockerfile: Dockerfile.facenet
    network_mode: host
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
